#name: Bifrost Test Run
#
#on:
#  push:
#    branches:
#      - main
#  schedule:
#    - cron: '* 6 * * *'
#
#jobs:
#  bifrostTestRun:
#    name: Bifrost Test Run
#    runs-on: ubuntu-18.04
#
#    steps:
#      - uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: 11
#          cache: gradle
#      - name: Bifrost Unit tests
#        run: bash ./gradlew test --stacktrace
#      - name: Notify Slack Error Test Run
#        if: failure()
#        env:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#        uses: abinoda/slack-action@master
#        with:s
#          args: '{\"channel\":\"C030FC8PY0N\",\"text\":\"Bifrost Test Run failed :x:\"}'
#      - name: Notify Slack Success Test Run
#        if: success()
#        env:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#        uses: abinoda/slack-action@master
#        with:
#          args: '{\"channel\":\"C030FC8PY0N\",\"text\":\"Bifrost Test Run Has Completely Successful :white_check_mark:\"}'

# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.

name: AutoRelease

on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
          regex: "/^Release: #{semver}$/i"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
