name: Bifrost Test Run

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  bifrostTestRun:
    name: Bifrost Test Run
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v3
      ##- name: set up JDK 11
      ##  uses: actions/setup-java@v3
      ##  with:
       ##   distribution: 'zulu'
       ##   java-version: 11
       ##   cache: gradle
      ##- name: Bifrost Unit tests
       ## run: bash ./gradlew test --stacktrace
      - name: Slack Notification
        if: success() || failure()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: mobile-logs
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://storage.googleapis.com/fizbot-website-v2/sites/1/2022/01/FIZBOT-WHITE3.png
          SLACK_MESSAGE: 'Post Content :rocket:'
          SLACK_TITLE: Bifrost Test Run
          SLACK_USERNAME: Bifrost
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}