name: Bifrost Test Run

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  bifrostTestRun:
    name: Bifrost Test Run
    runs-on: ubuntu-18.04

    steps:
      ####- uses: actions/checkout@v3
#      - name: set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          distribution: 'zulu'
#          java-version: 11
#          cache: gradle
#      - name: Bifrost Unit tests
#        run: bash ./gradlew test --stacktrace
      - name: Notify Slack Error Test Run
        if: failure()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"C030FC8PY0N\",\"text\":\"Err\"}'
      - name: Notify Slack Success Test Run
        if: success()
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"C030FC8PY0N\",\"text\":\"Success\"}'

