name: PullRequestGradleTest

on:
  push:
    branches:
      - main

jobs:
  test:
    name: GradleTest
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'STAGING')

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Grant Permissions to gradlew
        run: chmod +x gradlew
      - name: Test
        run: ./gradle test

      - name: Test Success
        if: success()
        uses: actions/github-script@0.2.0
      - name: Test Fail
        if: failure()
        uses: actions/github-script@0.2.0