name: Android CI

on:
  push:
    branches: [ "main" ]

jobs:
  slack:
    runs-on: ubuntu-latest
    steps:
      - name: Notify Slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: pullreminders/slack-action@master
        with:
            args: '{\"channel\":\"C030FC8PY0N\",\"text\":\"Hello world\"}'
