name: Bifrost Test Run

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  bifrostTestRun:
    name: Bifrost Test Run
    runs-on: ubuntu-18.04

    steps:
     ## - uses: actions/checkout@v3
      ##- name: set up JDK 11
      ##  uses: actions/setup-java@v3
      ##  with:
       ##   distribution: 'zulu'
       ##   java-version: 11
       ##   cache: gradle
      ##- name: Bifrost Unit tests
       ## run: bash ./gradlew test --stacktrace
      - name: Notify slack
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        uses: abinoda/slack-action@master
        with:
          args: '{\"channel\":\"C030FC8PY0N\",\"text\":\"Hello world\"}'
      ##- name: Slack Notification
        ##if: success() || failure()
        ##uses: rtCamp/action-slack-notify@v2
        ##env:
          ##SLACK_CHANNEL: mobile-logs

