name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: "Release: $version"
          tag: "v$semver"
          draft: false
          regex: "/^Release: #{semver}$/i"
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: abinoda/slack-action@master
        if: contains(github.event.head_commit.message, 'Release:')
        with:
          args: '{\"channel\":\"C030FC8PY0N\",\"text\":\"Bifrost ${{ github.event.head_commit.message }} Has Published :rocket:\"}'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
